# -*- coding: utf-8 -*-
"""main

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kwwRcjMH3UPD5xzqsb3GSS89CBmEuw1P
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/samoletpanfilov/reinforcement_task.git
!git clone https://github.com/yursur/Samolet_hack.git
# %run /content/Samolet_hack/main.ipynb